### ISSUE TITLE
1.1 vs 1.2 in header

### ISSUE THREAD

**Issue by divansantana** [zellio/ansible-vault-mode#20]
Firstly this project is awesome. Thank you.

I see the header says 1.1 not 1.2.

Does that mean your project is not supporting the latest vault "standard"?

**Comment by zellio** [comment]
Thanks!

That is correct, this project was written before 1.2 existed.

I don't use Ansible professionally anymore so I may or may not get to this issue. Happy to accept and review pull requests.

**Comment by zellio** [comment]
This has now been resolved in release v0.4.2, please update from your package repositories and it should all work now.

**Comment by zellio** [comment]
This has been further expanded in v0.5.0 to support correct handling of vault-id and v1.2 of the vault file format
