### ISSUE TITLE
no indication on failure to decrypt

### ISSUE THREAD

**Issue by kra** [zellio/ansible-vault-mode#5]
I opened a file encrypted with ansible vault, using various tricks in the README in an attempt to automagically decrypt it. I did enough to successfully trigger the mode, as shown by the (YAML ansible-vault) major/minor mode string in the modeline. But the buffer is empty. I see nothing in the *Messages* buffer.

I assume I misconfigured something, but I don't see a way to troubleshoot it.

**Comment by zellio** [comment]
There should be a buffer created called `*ansible-vault-error*` which contains the errors from `ansible-vault` execution.

**Comment by zellio** [comment]
@kra - did that woerk for you?

**Comment by kra** [comment]
I haven't been able to check! But this untested doc pull request hopefully docs it, which I consider working.

https://github.com/zellio/ansible-vault-mode/pull/7
