### ISSUE TITLE
Require statement in the Readme seems to be wrong

### ISSUE THREAD

**Issue by ceving** [zellio/ansible-vault-mode#6]
The Readme states than one should put the following in `.emacs`:

    (require 'ansible-vault-mode)

But the file is called `ansible-vault.el`.  So the correct initialization is:

    (require 'ansible-vault)

**Comment by zellio** [comment]
I honestly use `package.el` to handle auto loading this module and have no idea. Please file a pull request.

**Comment by chenz** [comment]
The file name should not matter, but rather what is _provided_:

    (provide 'ansible-vault)

So it should be `(require 'ansible-vault)` indeed.

**Comment by zellio** [comment]
@chenz - awesome, thank you for weighing in. I might be able to get to this in the coming weeks but if one of you could throw a pull request my way that would be fantastic. Thanks.

**Comment by zellio** [comment]
@lafrenierejm thank you for the PR. Upon further review however I think it will be better to migrate this package over to `ansible-vault-mode` which feels more correct as a name, rather than stick with `ansible vault.

**Comment by lafrenierejm** [comment]
@zellio Can this be closed now that #11 has been merged?

**Comment by zellio** [comment]
Yes.
