### ISSUE TITLE
ansible-vault 2.3.0 doesn't take STDIN

### ISSUE THREAD

**Issue by tzz** [zellio/ansible-vault-mode#8]
I resolved it with this override:

```
  ;; OVERRIDE: 2.3.0 doesn't accept STDIN anymore
  (defun ansible-vault-decrypt-current-buffer ()
    "In place decryption of `current-buffer' using `ansible-vault'."
    (let ((inhibit-read-only t))
      (let ((tf (make-temp-file "ansible-vault-mode-")))
        (write-region (point-min) (point-max) tf)
        (shell-command-on-region
         (point-min) (point-max)
         (concat (ansible-vault--call-command 'decrypt) " " tf)
         (current-buffer) t
         (ansible-vault--error-buffer))
        (delete-file tf))))
```

I hope that helps. I don't know if there's a better fix but this was a quick one and worked for me.

**Comment by zellio** [comment]
@tzz - I'd rather this get fixed upstream in `ansible-vault` as writing a temp file kinda defeats the purpose of the module in my opinion and this worked last version. I've filed a bug, let's see where it goes.

**Comment by zellio** [comment]
https://github.com/ansible/ansible/pull/23583

**Comment by zellio** [comment]
This will be fixed in v2.3.1 of ansible

**Comment by tzz** [comment]
Maybe the code should check for 2.3.0 and warn the user? I agree workarounds suck but the current situation is pretty bad from a usability standpoint.

**Comment by zellio** [comment]
Sorry I never got to this issue. I don't really use ansible anymore. I think it is safe to say that this issue is old enough to just resolve out right. If you think it's still worth monkey patching please re-file.
