### ISSUE TITLE
Ask for password when needed

### ISSUE THREAD

**Issue by mattiasb** [zellio/ansible-vault-mode#9]
When opening a vault-encrypted file with `ansible-vault-mode` and not having a `~/.vault_pass` file I just get an empty buffer and no errors just like in #5 . The assumption from the user is then of course that the file is just empty.

Solve this by asking the user to provide a password to decrypt the file manually when the decryption failed.

**Comment by mattiasb** [comment]
This mode should probably respect the `ANSIBLE_VAULT_PASSWORD_FILE` environment variable as well. I have that set to a little adapter script that queries lastpass for a password for the current repo right now for example and it works fine in the terminal and does nothing with `ansible-vault-mode`.

**Comment by ronaldevers** [comment]
I was playing with this as well. I'm using the following with today's MELPA version (>0.3.4) and can confirm this respects the `ANSIBLE_VAULT_PASSWORD_FILE` environment variable. Make sure the variable is actually set inside your Emacs, in `process-environment` I think.

```elisp
  (use-package ansible-vault
    :pin melpa
    :init
    (defun ansible-vault-mode-maybe ()
      (when (ansible-vault--is-vault-file)
        (ansible-vault-mode 1)))
    (setq ansible-vault-pass-file nil)
    :hook (yaml-mode . ansible-vault-mode-maybe))
```

I didn't look at the comments but I expect the `(if ansible-vault-pass-file ..)` was added in the call-command thing for this use-case.

**Comment by mattiasb** [comment]
Setting `ansible-vault-pass-file` to `(getenv "ANSIBLE_VAULT_PASSWORD_FILE")` got it kind of working. Now I need to see if there's any bugs with my password script, because I got some other errors when saving now.

**Comment by lafrenierejm** [comment]
I looked into prompting the user when the `ansible-vault` process requests a password.  `ansible-vault` uses Python's `getpass` to retrieve the password.

The various Emacs shell modes appear to use `send-invisible` when handling passwords:

> Read a string without echoing.
> Then send it to the process running in the current buffer.
> The string is sent using ‘comint-input-sender’.

I think a way forward might be to run `ansible-vault` in its own comint-inheriting buffer.  I haven't looked deeply into implementing this yet.

**Comment by zellio** [comment]
Okay, I've merged in `feature/smarter-passwords` which handles prompting for a password and properly detecting Ansible configurations. Password management should be a lot more sane now. I'm going to consider this issue closed. If there are bugs in the new `0.4.0` please file a new issue.

**Comment by mattiasb** [comment]
It seems to work fine! Great work @zellio !
